version: '3'
services: 
    server:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ENCRYPTION_KEY=${ENCRYPTION_KEY}
            - AUTHENTICATION_KEY=${AUTHENTICATION_KEY}
            - DSN=${DSN}
            - ADDR=${ADDR}
            - TLS=${TLS}
        ports: 
            - "${ADDR}:${ADDR}"
        volumes: 
            - ~/tls:/build/tls
        network_mode: "host"
